import nltk
try:
    nltk.data.find('tokenizers/punkt')
    nltk.data.find('taggers/averaged_perceptron_tagger')
except LookupError:
    
    nltk.download('punkt')
    nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize
import random
import json

VERBS={
    "Present Continuous": {
        "I": [
            "am",
            "am having",
            "am doing",
            "am saying",
            "am getting",
            "am making",
            "am going",
            "am knowing",
            "am taking",
            "am seeing",
            "am coming",
            "am thinking",
            "am looking",
            "am wanting",
            "am giving",
            "am using",
            "am finding",
            "am telling",
            "am asking",
            "am working",
            "am seeming",
            "am feeling",
            "am trying",
            "am leaving",
            "am calling",
            "'m",
            "'m having",
            "'m doing",
            "'m saying",
            "'m getting",
            "'m making",
            "'m going",
            "'m knowing",
            "'m taking",
            "'m seeing",
            "'m coming",
            "'m thinking",
            "'m looking",
            "'m wanting",
            "'m giving",
            "'m using",
            "'m finding",
            "'m telling",
            "'m asking",
            "'m working",
            "'m seeming",
            "'m feeling",
            "'m trying",
            "'m leaving",
            "'m calling"
        ],
        "he": [
            "is",
            "is having",
            "is doing",
            "is saying",
            "is getting",
            "is making",
            "is going",
            "is knowing",
            "is taking",
            "is seeing",
            "is coming",
            "is thinking",
            "is looking",
            "is wanting",
            "is giving",
            "is using",
            "is finding",
            "is telling",
            "is asking",
            "is working",
            "is seeming",
            "is feeling",
            "is trying",
            "is leaving",
            "is calling",
            "'s",
            "'s having",
            "'s doing",
            "'s saying",
            "'s getting",
            "'s making",
            "'s going",
            "'s knowing",
            "'s taking",
            "'s seeing",
            "'s coming",
            "'s thinking",
            "'s looking",
            "'s wanting",
            "'s giving",
            "'s using",
            "'s finding",
            "'s telling",
            "'s asking",
            "'s working",
            "'s seeming",
            "'s feeling",
            "'s trying",
            "'s leaving",
            "'s calling"
        ],
        "it": [
            "is",
            "is having",
            "is doing",
            "is saying",
            "is getting",
            "is making",
            "is going",
            "is knowing",
            "is taking",
            "is seeing",
            "is coming",
            "is thinking",
            "is looking",
            "is wanting",
            "is giving",
            "is using",
            "is finding",
            "is telling",
            "is asking",
            "is working",
            "is seeming",
            "is feeling",
            "is trying",
            "is leaving",
            "is calling",
            "'s",
            "'s having",
            "'s doing",
            "'s saying",
            "'s getting",
            "'s making",
            "'s going",
            "'s knowing",
            "'s taking",
            "'s seeing",
            "'s coming",
            "'s thinking",
            "'s looking",
            "'s wanting",
            "'s giving",
            "'s using",
            "'s finding",
            "'s telling",
            "'s asking",
            "'s working",
            "'s seeming",
            "'s feeling",
            "'s trying",
            "'s leaving",
            "'s calling"
        ],
        "she": [
            "is",
            "is having",
            "is doing",
            "is saying",
            "is getting",
            "is making",
            "is going",
            "is knowing",
            "is taking",
            "is seeing",
            "is coming",
            "is thinking",
            "is looking",
            "is wanting",
            "is giving",
            "is using",
            "is finding",
            "is telling",
            "is asking",
            "is working",
            "is seeming",
            "is feeling",
            "is trying",
            "is leaving",
            "is calling",
            "'s",
            "'s having",
            "'s doing",
            "'s saying",
            "'s getting",
            "'s making",
            "'s going",
            "'s knowing",
            "'s taking",
            "'s seeing",
            "'s coming",
            "'s thinking",
            "'s looking",
            "'s wanting",
            "'s giving",
            "'s using",
            "'s finding",
            "'s telling",
            "'s asking",
            "'s working",
            "'s seeming",
            "'s feeling",
            "'s trying",
            "'s leaving",
            "'s calling"
        ],
        "they": [
            "are",
            "are having",
            "are doing",
            "are saying",
            "are getting",
            "are making",
            "are going",
            "are knowing",
            "are taking",
            "are seeing",
            "are coming",
            "are thinking",
            "are looking",
            "are wanting",
            "are giving",
            "are using",
            "are finding",
            "are telling",
            "are asking",
            "are working",
            "are seeming",
            "are feeling",
            "are trying",
            "are leaving",
            "are calling",
            "'re",
            "'re having",
            "'re doing",
            "'re saying",
            "'re getting",
            "'re making",
            "'re going",
            "'re knowing",
            "'re taking",
            "'re seeing",
            "'re coming",
            "'re thinking",
            "'re looking",
            "'re wanting",
            "'re giving",
            "'re using",
            "'re finding",
            "'re telling",
            "'re asking",
            "'re working",
            "'re seeming",
            "'re feeling",
            "'re trying",
            "'re leaving",
            "'re calling"

        ],
        "we": [
            "are",
            "are having",
            "are doing",
            "are saying",
            "are getting",
            "are making",
            "are going",
            "are knowing",
            "are taking",
            "are seeing",
            "are coming",
            "are thinking",
            "are looking",
            "are wanting",
            "are giving",
            "are using",
            "are finding",
            "are telling",
            "are asking",
            "are working",
            "are seeming",
            "are feeling",
            "are trying",
            "are leaving",
            "are calling",
            "'re",
            "'re having",
            "'re doing",
            "'re saying",
            "'re getting",
            "'re making",
            "'re going",
            "'re knowing",
            "'re taking",
            "'re seeing",
            "'re coming",
            "'re thinking",
            "'re looking",
            "'re wanting",
            "'re giving",
            "'re using",
            "'re finding",
            "'re telling",
            "'re asking",
            "'re working",
            "'re seeming",
            "'re feeling",
            "'re trying",
            "'re leaving",
            "'re calling"
        ],
        "you": [
            "are",
            "are having",
            "are doing",
            "are saying",
            "are getting",
            "are making",
            "are going",
            "are knowing",
            "are taking",
            "are seeing",
            "are coming",
            "are thinking",
            "are looking",
            "are wanting",
            "are giving",
            "are using",
            "are finding",
            "are telling",
            "are asking",
            "are working",
            "are seeming",
            "are feeling",
            "are trying",
            "are leaving",
            "are calling",
            "'re",
            "'re having",
            "'re doing",
            "'re saying",
            "'re getting",
            "'re making",
            "'re going",
            "'re knowing",
            "'re taking",
            "'re seeing",
            "'re coming",
            "'re thinking",
            "'re looking",
            "'re wanting",
            "'re giving",
            "'re using",
            "'re finding",
            "'re telling",
            "'re asking",
            "'re working",
            "'re seeming",
            "'re feeling",
            "'re trying",
            "'re leaving",
            "'re calling"
        ]
    },
    "Present Perfect": {
        "I": [
            "have had",
            "have done",
            "have said",
            "have gotten",
            "have made",
            "have gone",
            "have known",
            "have taken",
            "have seen",
            "have come",
            "have thought",
            "have looked",
            "have wanted",
            "have given",
            "have used",
            "have found",
            "have told",
            "have asked",
            "have worked",
            "have seemed",
            "have felt",
            "have tried",
            "have left",
            "have called",
            "'ve had",
            "'ve done",
            "'ve said",
            "'ve gotten",
            "'ve made",
            "'ve gone",
            "'ve known",
            "'ve taken",
            "'ve seen",
            "'ve come",
            "'ve thought",
            "'ve looked",
            "'ve wanted",
            "'ve given",
            "'ve used",
            "'ve found",
            "'ve told",
            "'ve asked",
            "'ve worked",
            "'ve seemed",
            "'ve felt",
            "'ve tried",
            "'ve left",
            "'ve called"
        ],
        "he": [
            "has had",
            "has done",
            "has said",
            "has gotten",
            "has made",
            "has gone",
            "has known",
            "has taken",
            "has seen",
            "has come",
            "has thought",
            "has looked",
            "has wanted",
            "has given",
            "has used",
            "has found",
            "has told",
            "has asked",
            "has worked",
            "has seemed",
            "has felt",
            "has tried",
            "has left",
            "has called"
        ],
        "it": [
            "has had",
            "has done",
            "has said",
            "has gotten",
            "has made",
            "has gone",
            "has known",
            "has taken",
            "has seen",
            "has come",
            "has thought",
            "has looked",
            "has wanted",
            "has given",
            "has used",
            "has found",
            "has told",
            "has asked",
            "has worked",
            "has seemed",
            "has felt",
            "has tried",
            "has left",
            "has called"
        ],
        "she": [
            "has had",
            "has done",
            "has said",
            "has gotten",
            "has made",
            "has gone",
            "has known",
            "has taken",
            "has seen",
            "has come",
            "has thought",
            "has looked",
            "has wanted",
            "has given",
            "has used",
            "has found",
            "has told",
            "has asked",
            "has worked",
            "has seemed",
            "has felt",
            "has tried",
            "has left",
            "has called"
        ],
        "they": [
            "have had",
            "have done",
            "have said",
            "have gotten",
            "have made",
            "have gone",
            "have known",
            "have taken",
            "have seen",
            "have come",
            "have thought",
            "have looked",
            "have wanted",
            "have given",
            "have used",
            "have found",
            "have told",
            "have asked",
            "have worked",
            "have seemed",
            "have felt",
            "have tried",
            "have left",
            "have called",
            "'ve had",
            "'ve done",
            "'ve said",
            "'ve gotten",
            "'ve made",
            "'ve gone",
            "'ve known",
            "'ve taken",
            "'ve seen",
            "'ve come",
            "'ve thought",
            "'ve looked",
            "'ve wanted",
            "'ve given",
            "'ve used",
            "'ve found",
            "'ve told",
            "'ve asked",
            "'ve worked",
            "'ve seemed",
            "'ve felt",
            "'ve tried",
            "'ve left",
            "'ve called"
        ],
        "we": [
            "have had",
            "have done",
            "have said",
            "have gotten",
            "have made",
            "have gone",
            "have known",
            "have taken",
            "have seen",
            "have come",
            "have thought",
            "have looked",
            "have wanted",
            "have given",
            "have used",
            "have found",
            "have told",
            "have asked",
            "have worked",
            "have seemed",
            "have felt",
            "have tried",
            "have left",
            "have called",
            "'ve had",
            "'ve done",
            "'ve said",
            "'ve gotten",
            "'ve made",
            "'ve gone",
            "'ve known",
            "'ve taken",
            "'ve seen",
            "'ve come",
            "'ve thought",
            "'ve looked",
            "'ve wanted",
            "'ve given",
            "'ve used",
            "'ve found",
            "'ve told",
            "'ve asked",
            "'ve worked",
            "'ve seemed",
            "'ve felt",
            "'ve tried",
            "'ve left",
            "'ve called"
        ],
        "you": [
            "have had",
            "have done",
            "have said",
            "have gotten",
            "have made",
            "have gone",
            "have known",
            "have taken",
            "have seen",
            "have come",
            "have thought",
            "have looked",
            "have wanted",
            "have given",
            "have used",
            "have found",
            "have told",
            "have asked",
            "have worked",
            "have seemed",
            "have felt",
            "have tried",
            "have left",
            "have called",
            "'ve had",
            "'ve done",
            "'ve said",
            "'ve gotten",
            "'ve made",
            "'ve gone",
            "'ve known",
            "'ve taken",
            "'ve seen",
            "'ve come",
            "'ve thought",
            "'ve looked",
            "'ve wanted",
            "'ve given",
            "'ve used",
            "'ve found",
            "'ve told",
            "'ve asked",
            "'ve worked",
            "'ve seemed",
            "'ve felt",
            "'ve tried",
            "'ve left",
            "'ve called"
        ]
    },
    "Present Simple": {
        "I": [
            "am",
            "have",
            "do",
            "say",
            "get",
            "make",
            "go",
            "know",
            "take",
            "see",
            "come",
            "think",
            "look",
            "want",
            "give",
            "use",
            "find",
            "tell",
            "ask",
            "work",
            "seem",
            "feel",
            "try",
            "leave",
            "call"
        ],
        "he": [
            "is",
            "has",
            "does",
            "says",
            "gets",
            "makes",
            "goes",
            "knows",
            "takes",
            "sees",
            "comes",
            "thinks",
            "looks",
            "wants",
            "gives",
            "uses",
            "finds",
            "tells",
            "asks",
            "works",
            "seems",
            "feels",
            "tries",
            "leaves",
            "calls"
        ],
        "it": [
            "is",
            "has",
            "does",
            "says",
            "gets",
            "makes",
            "goes",
            "knows",
            "takes",
            "sees",
            "comes",
            "thinks",
            "looks",
            "wants",
            "gives",
            "uses",
            "finds",
            "tells",
            "asks",
            "works",
            "seems",
            "feels",
            "tries",
            "leaves",
            "calls"
        ],
        "she": [
            "is",
            "has",
            "does",
            "says",
            "gets",
            "makes",
            "goes",
            "knows",
            "takes",
            "sees",
            "comes",
            "thinks",
            "looks",
            "wants",
            "gives",
            "uses",
            "finds",
            "tells",
            "asks",
            "works",
            "seems",
            "feels",
            "tries",
            "leaves",
            "calls"
        ],
        "they": [
            "are",
            "have",
            "do",
            "say",
            "get",
            "make",
            "go",
            "know",
            "take",
            "see",
            "come",
            "think",
            "look",
            "want",
            "give",
            "use",
            "find",
            "tell",
            "ask",
            "work",
            "seem",
            "feel",
            "try",
            "leave",
            "call"
        ],
        "we": [
            "are",
            "have",
            "do",
            "say",
            "get",
            "make",
            "go",
            "know",
            "take",
            "see",
            "come",
            "think",
            "look",
            "want",
            "give",
            "use",
            "find",
            "tell",
            "ask",
            "work",
            "seem",
            "feel",
            "try",
            "leave",
            "call"
        ],
        "you": [
            "are",
            "have",
            "do",
            "say",
            "get",
            "make",
            "go",
            "know",
            "take",
            "see",
            "come",
            "think",
            "look",
            "want",
            "give",
            "use",
            "find",
            "tell",
            "ask",
            "work",
            "seem",
            "feel",
            "try",
            "leave",
            "call"
        ]
    }
}

reflections = {
    "i am" : "you are",
    "you are" : "I am",
    "i was" : "you were",
    "you were" : "I was",
    "i" : "you",
    "me" : "you",
    "my" : "your",
    "mine" : "yours",
    "you" : "me",
    "your" : "my",
    "he is" : "he is",
    "she is" : "she is",
    "it is" : "it is",
    "we are" : "we are",
    "they are" : "they are",
    "he was" : "he was",
    "she was" : "she was",
    "it was" : "it was",
    "we were" : "we were",
    "they were" : "they were",
    "his" : "his",
    "hers" : "hers",
    "its" : "its",
    "our" : "our",
    "theirs" : "theirs",
    "i'm" : "you are",
    "you're" : "I am",
    "he'd" : "he would",
    "she'd" : "she would",
    "it'd" : "it would",
    "we'd" : "we would",
    "they'd" : "they would",
    "i'd" : "you would",
    "you would" : "I would",
    "he's" : "he is",
    "she's" : "she is",
    "it's" : "it is",
    "we're" : "we are",
    "they're" : "they are",
    "i've" : "you have",
    "you've" : "I have",
    "he'll" : "he will",
    "she'll" : "she will",
    "it'll" : "it will",
    "we'll" : "we will",
    "they'll" : "they will",
    "i'll" : "you will",
    "you'll" : "I will"
    }


dont_understand = [
"I apologize, but I'm not quite sure I understand your question.",
"I'm having trouble comprehending your question, could you please rephrase it?",
"I'm sorry, I'm having difficulty interpreting your question. Could you please provide more context?",
"I'm not quite certain what you're asking. Could you please clarify or provide more information?",
"I'm afraid I'm having difficulty following your question. Can you elaborate further?",
"Regrettably, I'm not sure that I completely understand your question. Would you mind restating it?",
"I apologize, but I'm having a hard time comprehending your question. Could you please rephrase it in a different way?",
"I'm sorry, but your question is unclear to me. Can you please provide additional details or context to help me better understand?",
"I'm not sure I understand your question correctly. Would you mind explaining it in more detail, please?",
"I'm sorry if I'm mistaken, but it seems like I'm having difficulty understanding your question. Can you explain further?"
]
def get_POS_tag(q):
    tokens = word_tokenize(q)
    pos_tags = nltk.pos_tag(tokens)
    return pos_tags[0][1]
def is_YN_question(sent):
    l=[]
    for x in VERBS:
        for y in VERBS[x]:
            for z in VERBS[x][y]:
                pp=word_tokenize(y+" "+z)
                pp[0], pp[1]= pp[1],pp[0]
                if len(pp)>2:
                    del pp[2]
                for i in range(len(pp)):
                    pp[i]=pp[i].lower()   
                if ' '.join(pp) not in l:
                    l.append(' '.join(pp))
                for w in pp:
                    if ' '.join(pp) in sent:
                        return True,' '.join(pp)
                        break

def return_answer(question):
    try:
        YN=random.choice(['Yes','No'])
        question=question.lower()
        YN_question=is_YN_question(question)
        if YN_question[0]==True:
            inv=word_tokenize(YN_question[1])
            inv[0],inv[1]=inv[1],inv[0]
            answer=question.replace(YN_question[1],' '.join(inv))
            yes_or_no=YN
            if yes_or_no=='Yes':
                answer=answer.replace(' '.join(inv),"Yes, "+reflections[' '.join(inv)])
            else:
                answer=answer.replace(' '.join(inv),"No, "+reflections[' '.join(inv)]+" not ")
        answer=answer.replace("?","")
        answer=word_tokenize(answer)
        for o in range(len(answer)):
            if get_POS_tag(answer[o])=='PRP$':
               if answer[o] in reflections.keys():
                  answer[o]=reflections[answer[o]]
        answer=' '.join(answer)

        
        
        return answer
    except:
            return random.choice(dont_understand)